#!/bin/bash

OS_ID=${OS_ID:-c3os}
IMAGE="${IMAGE:-$OS_ID}"
ISO="${ISO:-$OS_ID}"
FLAVOR="${FLAVOR:-opensuse}"
C3OS_VERSION="${C3OS_VERSION:--c3OS40}"
K3S_VERSION="${K3S_VERSION:-v1.21.4+k3s1}"
OS_LABEL="${OS_LABEL:-$FLAVOR-latest}"
OS_NAME="${OS_NAME:-$OS_ID-$FLAVOR}"
LUET_VERSION="${LUET_VERSION:-0.22.7-1}"
