package tui

import (
	"fmt"

	sdkConfig "github.com/kairos-io/kairos-sdk/types/config"
	sdkInstall "github.com/kairos-io/kairos-sdk/types/install"
	"github.com/mudler/yip/pkg/schema"
	"gopkg.in/yaml.v3"
)

// yip stage names (copied from kairos-agent pkg/config).
const (
	networkStage   = "network"
	initramfsStage = "initramfs"
)

// extraFields wraps the dynamic plugin fields so they inline at the top level.
type extraFields struct {
	Extrafields map[string]any `yaml:",inline,omitempty"`
}

// RenderCloudConfig turns the collected Model into a #cloud-config document.
// Unlike the agent's original NewInteractiveInstallConfig, it intentionally does
// NOT merge the system userdata dirs here: kairos-agent manual-install is invoked
// with --use-default-dirs, which re-scans those dirs at install time.
func RenderCloudConfig(m *Model) (string, error) {
	extras := extraFields{m.extraFields}

	cc := &sdkConfig.Config{
		Install: &sdkInstall.Install{
			Device: m.disk,
		},
	}
	if m.source != "" {
		cc.Install.Source = m.source
	}
	switch m.finishAction {
	case "reboot":
		cc.Install.Reboot = true
	case "poweroff":
		cc.Install.Poweroff = true
	}

	var cloudConfig schema.YipConfig
	if m.username != "" {
		user := schema.User{
			Name:              m.username,
			PasswordHash:      m.password,
			Groups:            []string{"admin"},
			SSHAuthorizedKeys: m.sshKeys,
		}
		stage := networkStage
		if len(m.sshKeys) == 0 {
			stage = initramfsStage
		}
		cloudConfig = schema.YipConfig{
			Name: "Config generated by the installer",
			Stages: map[string][]schema.Stage{stage: {
				{Users: map[string]schema.User{m.username: user}},
			}},
		}
	} else {
		cc.Install.NoUsers = true
	}

	dat, err := mergeYAML(cloudConfig, cc, extras)
	if err != nil {
		return "", err
	}
	return addHeader("#cloud-config", string(dat)), nil
}

// RenderRedactedCloudConfig renders the cloud-config with the user password
// replaced, for safe inclusion in debug bundles. The input model is not mutated.
func RenderRedactedCloudConfig(m *Model) (string, error) {
	clone := *m
	if clone.password != "" {
		clone.password = "***REDACTED***"
	}
	return RenderCloudConfig(&clone)
}

// mergeYAML merges objects into a single YAML document (copied from kairos-agent).
func mergeYAML(objs ...interface{}) ([]byte, error) {
	finalData := make(map[string]interface{})
	for _, o := range objs {
		dat, err := yaml.Marshal(o)
		if err != nil {
			return nil, err
		}
		if err := yaml.Unmarshal(dat, &finalData); err != nil {
			return nil, err
		}
	}
	return yaml.Marshal(finalData)
}

func addHeader(header, data string) string {
	return fmt.Sprintf("%s\n%s", header, data)
}
