package tui

import (
	"os"
	"path/filepath"

	tea "github.com/charmbracelet/bubbletea"
	sdkLogger "github.com/kairos-io/kairos/v4/sdk/types/logger"
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("RenderCloudConfig", func() {
	It("renders a user stage with ssh keys at the network stage", func() {
		m := &Model{
			disk:         "/dev/sda",
			username:     "kairos",
			passwordHash: "$6$salt$hashhash",
			sshKeys:      []string{"ssh-ed25519 AAAA"},
			finishAction: "reboot",
		}
		out, err := RenderCloudConfig(m)
		Expect(err).ToNot(HaveOccurred())
		Expect(out).To(Equal(`#cloud-config
install:
    device: /dev/sda
    reboot: true
name: Config generated by the installer
stages:
    network:
        - users:
            kairos:
                groups:
                    - admin
                name: kairos
                passwd: $6$salt$hashhash
                ssh_authorized_keys:
                    - ssh-ed25519 AAAA
`))
	})

	It("sets no_users and no user stage when no username is given", func() {
		m := &Model{disk: "/dev/sda", finishAction: "nothing"}
		out, err := RenderCloudConfig(m)
		Expect(err).ToNot(HaveOccurred())
		Expect(out).To(ContainSubstring("nousers: true"))
		Expect(out).ToNot(ContainSubstring("network:"))
	})

	It("uses the initramfs stage when there are no ssh keys", func() {
		m := &Model{disk: "/dev/sda", username: "kairos", passwordHash: "$6$salt$x"}
		out, err := RenderCloudConfig(m)
		Expect(err).ToNot(HaveOccurred())
		Expect(out).To(ContainSubstring("initramfs:"))
	})
})

var _ = Describe("RenderRedactedCloudConfig", func() {
	It("replaces the password and never leaks the original hash", func() {
		oldHasher := passwordHasher
		DeferCleanup(func() { passwordHasher = oldHasher })
		passwordHasher = func(password string) (string, error) {
			Expect(password).To(Equal("cleartext-sentinel"))
			return "$6$salt$supersecrethash", nil
		}
		mainModel = Model{disk: "/dev/sda", sshKeys: []string{"ssh-ed25519 AAAA"}}
		page := newUserPasswordPage()
		page.usernameInput.SetValue("kairos")
		page.passwordInput.SetValue("cleartext-sentinel")
		_, cmd := page.Update(tea.KeyMsg{Type: tea.KeyEnter})
		Expect(cmd).NotTo(BeNil())

		out, err := RenderRedactedCloudConfig(&mainModel)
		Expect(err).ToNot(HaveOccurred())
		Expect(out).To(ContainSubstring("***REDACTED***"))
		Expect(out).ToNot(ContainSubstring("supersecrethash"))
		Expect(out).ToNot(ContainSubstring("cleartext-sentinel"))
	})

	It("leaves the original model untouched", func() {
		m := &Model{disk: "/dev/sda", username: "kairos", passwordHash: "$6$salt$supersecrethash"}
		_, err := RenderRedactedCloudConfig(m)
		Expect(err).ToNot(HaveOccurred())
		Expect(m.passwordHash).To(Equal("$6$salt$supersecrethash"))
	})
})

var _ = Describe("installProcessPage agent resolution", func() {
	It("reports an error and leaves no temp config when kairos-agent is absent", func() {
		// No agent anywhere.
		GinkgoT().Setenv("KAIROS_AGENT_BIN", "")
		GinkgoT().Setenv("PATH", GinkgoT().TempDir())

		// Minimal valid model for RenderCloudConfig.
		logger := sdkLogger.NewKairosLogger("installer", "info", true)
		mainModel = InitialModel(&logger, "") // resets global mainModel
		mainModel.disk = "/dev/sda"
		mainModel.finishAction = "nothing"

		before := tmpConfigCount()
		p := newInstallProcessPage()
		p.Init()
		Expect(p.errorMsg).To(ContainSubstring("kairos-agent not found"))
		Expect(tmpConfigCount()).To(Equal(before)) // no kairos-install-*.yaml leaked
	})
})

// tmpConfigCount counts leftover temp cloud-config files.
func tmpConfigCount() int {
	matches, _ := filepath.Glob(filepath.Join(os.TempDir(), "kairos-install-*.yaml"))
	return len(matches)
}
