package extensions

import (
	"os"
	"testing"
)

// testdata/releases.json is an excerpt of the index hadron-layers publishes to
// https://kairos-io.github.io/hadron-layers/releases.json, with the digests and
// the layer set as they were on 2026-09-01. The index is generated by
// hadron-layers' site/build-data.sh for a static web page, so nothing over
// there pins the shape this parser depends on. These tests are that pin: if
// build-data.sh changes a field name or nests the artifacts differently, they
// fail here instead of the agent failing on a node.
//
// To refresh the fixture, download the published index and trim it to a couple
// of layers.
func loadPublishedCatalog(t *testing.T) Catalog {
	t.Helper()
	file, err := os.Open("testdata/releases.json")
	if err != nil {
		t.Fatal(err)
	}
	defer file.Close()
	catalog, err := Parse(file)
	if err != nil {
		t.Fatalf("the published index no longer parses: %v", err)
	}
	return catalog
}

func TestPublishedCatalogResolvesToADigestPinnedArtifact(t *testing.T) {
	catalog := loadPublishedCatalog(t)

	if catalog.Repository != "kairos-io/hadron-layers" {
		t.Errorf("Repository = %q, want the repo field of the published index", catalog.Repository)
	}

	// A bare name has to reach an artifact through the layer's own `latest`,
	// which is what `kairos-agent sysext install fwupd` does.
	got, err := catalog.Resolve("fwupd", "", "amd64")
	if err != nil {
		t.Fatalf("Resolve(fwupd, latest, amd64): %v", err)
	}
	want := Resolved{
		Repository:   "kairos-io/hadron-layers",
		Name:         "fwupd",
		Version:      "2.1.7",
		Architecture: "amd64",
		OCI:          "ghcr.io/kairos-io/hadron-layers/sysext/fwupd@sha256:41767043b6016c222174722e70d84ea8b2402a50464543851b74b3e6c2941a05",
	}
	if got != want {
		t.Fatalf("Resolve() = %#v, want %#v", got, want)
	}

	if _, err := catalog.Resolve("fwupd", "", "arm64"); err != nil {
		t.Errorf("Resolve(fwupd, latest, arm64): %v", err)
	}
}

func TestPublishedCatalogRejectsLayersWithNoArtifacts(t *testing.T) {
	catalog := loadPublishedCatalog(t)

	// A layer is published as an image even when the sysext build is skipped,
	// so the index carries entries with an empty `sysext` object. Asking for
	// one has to fail with the architecture named, not resolve to nothing.
	if _, err := catalog.Resolve("git", "", "amd64"); err == nil {
		t.Fatal("Resolve(git) succeeded, want an error: the layer publishes no sysext artifact")
	}

	// Same for an older version of a layer whose newest version does publish.
	if _, err := catalog.Resolve("fwupd", "2.1.6", "amd64"); err == nil {
		t.Fatal("Resolve(fwupd, 2.1.6) succeeded, want an error: that version publishes no sysext artifact")
	}
}
