ARG FLAVOR=24.04

FROM golang AS build
WORKDIR /app
RUN git clone https://github.com/Itxaka/kairos-init.git .
RUN go mod download
ENV CGO_ENABLED=0
RUN go build -o /app/kairos-init .

FROM ubuntu:${FLAVOR} AS kairos
COPY --from=build /app/kairos-init /kairos-init
RUN /kairos-init -l debug -f immutability
RUN /kairos-init -l debug -f kernel
RUN /kairos-init -l debug -f initrd
RUN /kairos-init -l debug -f release
RUN /kairos-init -l debug -f clean
RUN rm /kairos-init