ARG BASE_IMAGE=ubuntu:20.04
ARG MODEL=generic

FROM $BASE_IMAGE as base
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get install -y software-properties-common \
    && add-apt-repository ppa:oibaf/test \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

FROM base AS generic
RUN apt-get update && apt-get install -y linux-base \
    linux-image-generic-hwe-22.04 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

FROM base AS rpi64
# Normally we install also linux-modules-extra-raspi but this is not available for 20.04, not sure what's the impact to
# remove it.
RUN apt-get update && apt-get install -y linux-firmware-raspi2 \
    linux-raspi \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

FROM ${MODEL} AS all

FROM all
RUN apt-get update && apt-get install -y \
    conntrack \
    console-data \
    coreutils \
    curl \
    debianutils \
    dosfstools \
    dracut \
    dracut-network \
    e2fsprogs \
    gawk \
    gdisk \
    grub2-common \
    grub-efi-arm64-bin \
    haveged \
    iproute2 \
    iptables \
    jq \
    linux-firmware-raspi2 \
    linux-raspi \
    lldpd \
    nano \
    neovim \
    openssh-server \
    open-vm-tools \
    parted \
    policykit-1 \
    rpi-eeprom \
    rsync \
    snapd \
    snmpd \
    squashfs-tools \
    sudo \
    systemd \
    systemd-timesyncd \
    tar \
    && apt-get remove -y unattended-upgrades && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/sbin/grub-install /usr/sbin/grub2-install
RUN ln -s /usr/bin/grub-editenv /usr/bin/grub2-editenv
RUN systemctl enable systemd-networkd
RUN systemctl enable ssh
RUN systemctl disable rpi-eeprom-update

# Fixup sudo perms
RUN chown root:root /usr/bin/sudo && chmod 4755 /usr/bin/sudo


# Clear cache
RUN rm -rf /var/cache/* && journalctl --vacuum-size=1K && rm /etc/machine-id && rm /var/lib/dbus/machine-id && rm /etc/hostname
