package wizard_test

import (
	sdkExtensions "github.com/kairos-io/kairos/v4/sdk/types/extensions"
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	"gopkg.in/yaml.v3"

	"github.com/kairos-io/kairos/v4/installer/internal/wizard"
)

var _ = Describe("Render", func() {
	It("renders a user stage with ssh keys at the network stage, byte for byte as the TUI did", func() {
		out, err := wizard.Render(wizard.Answers{
			Disk: "/dev/sda", Username: "kairos", PasswordHash: "$6$salt$hashhash",
			SSHKeys: []string{"ssh-ed25519 AAAA"}, FinishAction: wizard.FinishReboot,
		})
		Expect(err).ToNot(HaveOccurred())
		Expect(out).To(Equal(`#cloud-config
install:
    device: /dev/sda
    reboot: true
name: Config generated by the installer
stages:
    network:
        - users:
            kairos:
                groups:
                    - admin
                name: kairos
                passwd: $6$salt$hashhash
                ssh_authorized_keys:
                    - ssh-ed25519 AAAA
`))
	})

	It("sets nousers and writes no user stage when no username is given", func() {
		out, err := wizard.Render(wizard.Answers{Disk: "/dev/sda"})
		Expect(err).ToNot(HaveOccurred())
		Expect(out).To(ContainSubstring("nousers: true"))
		Expect(out).ToNot(ContainSubstring("network:"))
		Expect(out).ToNot(ContainSubstring("stages:"))
	})

	It("refuses ssh keys with no username rather than dropping them", func() {
		_, err := wizard.Render(wizard.Answers{Disk: "/dev/sda", SSHKeys: []string{"ssh-ed25519 AAAA"}})
		Expect(err).To(MatchError(ContainSubstring("nowhere to put them")))
	})

	It("uses the initramfs stage for the user when there are no ssh keys", func() {
		out, err := wizard.Render(wizard.Answers{Disk: "/dev/sda", Username: "kairos", PasswordHash: "$6$salt$x"})
		Expect(err).ToNot(HaveOccurred())
		Expect(out).To(ContainSubstring("initramfs:"))
	})

	It("writes the source, the extensions and poweroff into the install block", func() {
		out, err := wizard.Render(wizard.Answers{
			Disk: "/dev/sda", Source: "oci:quay.io/kairos/test:v1", FinishAction: wizard.FinishPoweroff,
			Extensions: sdkExtensions.Extensions{{Name: "/run/initramfs/live/k3s.sysext.raw"}, {Name: "tailscale"}},
		})
		Expect(err).ToNot(HaveOccurred())
		Expect(out).To(ContainSubstring("source: oci:quay.io/kairos/test:v1"))
		Expect(out).To(ContainSubstring("poweroff: true"))
		Expect(out).To(ContainSubstring("- /run/initramfs/live/k3s.sysext.raw"))
		Expect(out).To(ContainSubstring("- tailscale"))
		Expect(out).ToNot(ContainSubstring("reboot:"))
	})

	It("preserves extension versions in the install block", func() {
		out, err := wizard.Render(wizard.Answers{
			Disk:       "/dev/sda",
			Extensions: sdkExtensions.Extensions{{Name: "fwupd", Version: ">= 2.1"}},
		})
		Expect(err).ToNot(HaveOccurred())
		Expect(out).To(ContainSubstring("name: fwupd"))
		Expect(out).To(ContainSubstring("version:"))
		Expect(out).To(ContainSubstring(">= 2.1"))
	})

	It("merges provider fields at the top level", func() {
		out, err := wizard.Render(wizard.Answers{Disk: "/dev/sda", Provider: map[string]any{"k3s": map[string]any{"enabled": true}}})
		Expect(err).ToNot(HaveOccurred())
		Expect(out).To(ContainSubstring("k3s:\n    enabled: true\n"))
	})
})

var _ = Describe("Redact", func() {
	It("redacts every passwd key in hand-edited YAML, at any depth", func() {
		in := "#cloud-config\nusers:\n  - name: a\n    passwd: plain1\nstages:\n  boot:\n    - users:\n        b:\n          passwd: $6$x$secret2\n"
		out := wizard.Redact(in)
		Expect(out).ToNot(ContainSubstring("plain1"))
		Expect(out).ToNot(ContainSubstring("secret2"))
		Expect(out).To(HavePrefix("#cloud-config\n"))
	})

	It("returns a placeholder instead of the text when the YAML does not parse", func() {
		Expect(wizard.Redact("users: [unterminated\n  passwd: leak")).ToNot(ContainSubstring("leak"))
	})
})

var _ = Describe("Render, the settings added with the wizard", func() {
	// parse returns the initramfs stage list of a rendered document.
	parse := func(out string) []map[string]any {
		doc := map[string]any{}
		Expect(yaml.Unmarshal([]byte(out), &doc)).To(Succeed())
		stages, _ := doc["stages"].(map[string]any)
		list, _ := stages["initramfs"].([]any)
		var res []map[string]any
		for _, s := range list {
			res = append(res, s.(map[string]any))
		}
		return res
	}

	It("sets the hostname in the initramfs stage", func() {
		out, err := wizard.Render(wizard.Answers{Disk: "/dev/sda", Hostname: "edge-01"})
		Expect(err).ToNot(HaveOccurred())
		Expect(parse(out)).To(ContainElement(HaveKeyWithValue("hostname", "edge-01")))
	})

	It("links the timezone to /etc/localtime, only where the zone file exists", func() {
		out, err := wizard.Render(wizard.Answers{Disk: "/dev/sda", Timezone: "Europe/Rome"})
		Expect(err).ToNot(HaveOccurred())
		Expect(out).To(ContainSubstring("ln -sf /usr/share/zoneinfo/Europe/Rome /etc/localtime"))
		// ln -sf writes the link whether or not the target is there, and a
		// dangling /etc/localtime leaves the system on UTC while the
		// summary says otherwise. See kairos-io/kairos#5079.
		Expect(out).To(ContainSubstring("[ -e /usr/share/zoneinfo/Europe/Rome ]"))
	})

	It("writes the keymap for systemd, and for openrc only where conf.d exists", func() {
		out, err := wizard.Render(wizard.Answers{Disk: "/dev/sda", Keymap: "it"})
		Expect(err).ToNot(HaveOccurred())
		stages := parse(out)
		Expect(stages).To(HaveLen(2))
		Expect(stages[0]).ToNot(HaveKey("if"))
		Expect(out).To(ContainSubstring("path: /etc/vconsole.conf"))
		Expect(out).To(ContainSubstring("KEYMAP=it"))
		Expect(stages[1]).To(HaveKeyWithValue("if", "[ -d /etc/conf.d ]"))
		Expect(out).To(ContainSubstring(`keymap="it"`))
	})

	It("keeps the new settings before the user, in one initramfs stage list", func() {
		out, err := wizard.Render(wizard.Answers{Disk: "/dev/sda", Hostname: "h", Username: "kairos", PasswordHash: "$6$x$y"})
		Expect(err).ToNot(HaveOccurred())
		stages := parse(out)
		Expect(stages).To(HaveLen(2))
		Expect(stages[0]).To(HaveKey("hostname"))
		Expect(stages[1]).To(HaveKey("users"))
	})

	It("writes nothing for settings left empty", func() {
		out, err := wizard.Render(wizard.Answers{Disk: "/dev/sda", Username: "kairos", PasswordHash: "$6$x$y"})
		Expect(err).ToNot(HaveOccurred())
		Expect(out).ToNot(ContainSubstring("hostname"))
		Expect(out).ToNot(ContainSubstring("zoneinfo"))
		Expect(out).ToNot(ContainSubstring("vconsole"))
	})
})

var _ = Describe("Render, on answers that did not come through Apply", func() {
	// /api/render takes the answers straight from the browser, so Render
	// checks what it writes into a command or a file itself.
	DescribeTable("refuses a value Apply would have refused",
		func(a wizard.Answers, field string) {
			a.Disk = "/dev/sda"
			out, err := wizard.Render(a)
			Expect(err).To(HaveOccurred())
			Expect(err.Error()).To(ContainSubstring(field))
			Expect(out).To(BeEmpty())
		},
		Entry("shell in timezone", wizard.Answers{Timezone: "UTC; reboot"}, "timezone"),
		Entry("path traversal in timezone", wizard.Answers{Timezone: "../../etc/shadow"}, "timezone"),
		Entry("newline in keymap", wizard.Answers{Keymap: "it\nKEYMAP=us"}, "keymap"),
		Entry("quote in keymap", wizard.Answers{Keymap: `it"`}, "keymap"),
		Entry("shell in hostname", wizard.Answers{Hostname: "a;reboot"}, "hostname"),
	)

	It("still renders valid values", func() {
		_, err := wizard.Render(wizard.Answers{Disk: "/dev/sda", Timezone: "Etc/GMT+5", Keymap: "de-latin1", Hostname: "edge-01.lab"})
		Expect(err).ToNot(HaveOccurred())
	})
})
