package wizard

import (
	"fmt"

	sdkConfig "github.com/kairos-io/kairos/v4/sdk/types/config"
	sdkInstall "github.com/kairos-io/kairos/v4/sdk/types/install"
	"github.com/mudler/yip/pkg/schema"
	"gopkg.in/yaml.v3"
)

// yip stage names.
const (
	networkStage   = "network"
	initramfsStage = "initramfs"
)

const generatedName = "Config generated by the installer"

// Redacted replaces a password in anything written to a debug bundle.
const Redacted = "***REDACTED***"

// extraFields inlines the provider fields at the top level.
type extraFields struct {
	Extrafields map[string]any `yaml:",inline,omitempty"`
}

// Render turns the answers into a #cloud-config document.
//
// It does not merge the system userdata directories: kairos-agent
// manual-install runs with --use-default-dirs and reads them itself.
//
// Settings left empty write nothing, so an install that skips every optional
// step gets exactly the configuration it got before those steps existed.
//
// The answers may not have come through Apply: the web UI's /api/render takes
// them from the browser as they are. So Render checks the values it writes
// into a command or a file with the same checks Apply uses, and refuses the
// answers when one fails.
func Render(a Answers) (string, error) {
	if err := checkWritten(a); err != nil {
		return "", err
	}
	cc := &sdkConfig.Config{Install: &sdkInstall.Install{Device: a.Disk}}
	if a.Source != "" {
		cc.Install.Source = a.Source
	}
	if len(a.Extensions) > 0 {
		cc.Install.Extensions = a.Extensions
	}
	switch a.FinishAction {
	case FinishReboot:
		cc.Install.Reboot = true
	case FinishPoweroff:
		cc.Install.Poweroff = true
	}
	if a.Username == "" {
		cc.Install.NoUsers = true
	}

	stages := map[string][]schema.Stage{}
	add := func(stage string, s schema.Stage) { stages[stage] = append(stages[stage], s) }

	if a.Hostname != "" {
		add(initramfsStage, schema.Stage{Name: "Set the hostname", Hostname: a.Hostname})
	}
	if a.Timezone != "" {
		// checkWritten only lets a zoneinfo name through, so this cannot
		// be anything but a path under /usr/share/zoneinfo.
		//
		// Gated, because ln -sf writes the link whether or not the target
		// exists: an image with no time zone database would get a dangling
		// /etc/localtime and still run on UTC. Steps does not offer a
		// timezone on such an image, but Render also takes answers the web
		// UI sends straight from the browser.
		add(initramfsStage, schema.Stage{
			Name:     "Set the timezone",
			If:       fmt.Sprintf("[ -e /usr/share/zoneinfo/%s ]", a.Timezone),
			Commands: []string{fmt.Sprintf("ln -sf /usr/share/zoneinfo/%s /etc/localtime", a.Timezone)},
		})
	}
	if a.Keymap != "" {
		// systemd reads vconsole.conf, and on openrc the file is inert.
		add(initramfsStage, schema.Stage{
			Name:  "Set the keyboard layout",
			Files: []schema.File{{Path: "/etc/vconsole.conf", Permissions: 0644, Content: "KEYMAP=" + a.Keymap + "\n"}},
		})
		// openrc's keymaps service reads conf.d. Gated, because yip creates
		// a missing parent directory and a systemd image has no conf.d.
		add(initramfsStage, schema.Stage{
			Name:  "Set the keyboard layout for openrc",
			If:    "[ -d /etc/conf.d ]",
			Files: []schema.File{{Path: "/etc/conf.d/keymaps", Permissions: 0644, Content: fmt.Sprintf("keymap=%q\n", a.Keymap)}},
		})
	}
	if a.Username != "" {
		user := schema.User{
			Name:              a.Username,
			PasswordHash:      a.PasswordHash,
			Groups:            []string{"admin"},
			SSHAuthorizedKeys: a.SSHKeys,
		}
		// With keys, the user waits for the network stage, where github: and
		// gitlab: shorthands can be fetched.
		stage := networkStage
		if len(a.SSHKeys) == 0 {
			stage = initramfsStage
		}
		add(stage, schema.Stage{Users: map[string]schema.User{a.Username: user}})
	}

	var yc schema.YipConfig
	if len(stages) > 0 {
		yc = schema.YipConfig{Name: generatedName, Stages: stages}
	}

	dat, err := mergeYAML(yc, cc, extraFields{a.Provider})
	if err != nil {
		return "", err
	}
	return "#cloud-config\n" + string(dat), nil
}

// checkWritten refuses a hostname, timezone or keymap that Apply would have
// refused.
func checkWritten(a Answers) error {
	switch {
	case a.Hostname != "" && !validHostname(a.Hostname):
		return fmt.Errorf("the hostname %q is not a valid host name", a.Hostname)
	case a.Timezone != "" && !validTimezone(a.Timezone):
		return fmt.Errorf("the timezone %q is not a zoneinfo name", a.Timezone)
	case a.Keymap != "" && !validKeymap(a.Keymap):
		return fmt.Errorf("the keymap %q is not a keyboard layout name", a.Keymap)
	}
	return nil
}

// Redact replaces every passwd value in a cloud-config, at any depth, for a
// debug bundle. The text may have been edited by hand, so it cannot rely on
// the shape Render writes. A document that does not parse is replaced
// whole, since there is no way to know where a password is in it.
func Redact(cloudConfig string) string {
	var doc any
	if err := yaml.Unmarshal([]byte(cloudConfig), &doc); err != nil {
		return "#cloud-config\n# " + Redacted + " (the configuration did not parse)\n"
	}
	redactNode(doc)
	out, err := yaml.Marshal(doc)
	if err != nil {
		return "#cloud-config\n# " + Redacted + "\n"
	}
	return "#cloud-config\n" + string(out)
}

func redactNode(n any) {
	switch v := n.(type) {
	case map[string]any:
		for k, child := range v {
			if k == "passwd" {
				v[k] = Redacted
				continue
			}
			redactNode(child)
		}
	case []any:
		for _, child := range v {
			redactNode(child)
		}
	}
}

// mergeYAML merges objects into one YAML document, later objects winning.
func mergeYAML(objs ...any) ([]byte, error) {
	final := map[string]any{}
	for _, o := range objs {
		dat, err := yaml.Marshal(o)
		if err != nil {
			return nil, err
		}
		if err := yaml.Unmarshal(dat, &final); err != nil {
			return nil, err
		}
	}
	return yaml.Marshal(final)
}
