package wizard_test

import (
	sdkExtensions "github.com/kairos-io/kairos/v4/sdk/types/extensions"
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	"github.com/kairos-io/kairos/v4/installer/internal/wizard"
)

var _ = Describe("Render", func() {
	It("renders a user stage with ssh keys at the network stage, byte for byte as the TUI did", func() {
		out, err := wizard.Render(wizard.Answers{
			Disk: "/dev/sda", Username: "kairos", PasswordHash: "$6$salt$hashhash",
			SSHKeys: []string{"ssh-ed25519 AAAA"}, FinishAction: wizard.FinishReboot,
		})
		Expect(err).ToNot(HaveOccurred())
		Expect(out).To(Equal(`#cloud-config
install:
    device: /dev/sda
    reboot: true
name: Config generated by the installer
stages:
    network:
        - users:
            kairos:
                groups:
                    - admin
                name: kairos
                passwd: $6$salt$hashhash
                ssh_authorized_keys:
                    - ssh-ed25519 AAAA
`))
	})

	It("sets nousers and writes no user stage when no username is given", func() {
		out, err := wizard.Render(wizard.Answers{Disk: "/dev/sda"})
		Expect(err).ToNot(HaveOccurred())
		Expect(out).To(ContainSubstring("nousers: true"))
		Expect(out).ToNot(ContainSubstring("network:"))
		Expect(out).ToNot(ContainSubstring("stages:"))
	})

	It("uses the initramfs stage for the user when there are no ssh keys", func() {
		out, err := wizard.Render(wizard.Answers{Disk: "/dev/sda", Username: "kairos", PasswordHash: "$6$salt$x"})
		Expect(err).ToNot(HaveOccurred())
		Expect(out).To(ContainSubstring("initramfs:"))
	})

	It("writes the source, the extensions and poweroff into the install block", func() {
		out, err := wizard.Render(wizard.Answers{
			Disk: "/dev/sda", Source: "oci:quay.io/kairos/test:v1", FinishAction: wizard.FinishPoweroff,
			Extensions: sdkExtensions.Extensions{{Name: "/run/initramfs/live/k3s.sysext.raw"}, {Name: "tailscale"}},
		})
		Expect(err).ToNot(HaveOccurred())
		Expect(out).To(ContainSubstring("source: oci:quay.io/kairos/test:v1"))
		Expect(out).To(ContainSubstring("poweroff: true"))
		Expect(out).To(ContainSubstring("- name: /run/initramfs/live/k3s.sysext.raw"))
		Expect(out).To(ContainSubstring("- name: tailscale"))
		Expect(out).ToNot(ContainSubstring("reboot:"))
	})

	It("merges provider fields at the top level", func() {
		out, err := wizard.Render(wizard.Answers{Disk: "/dev/sda", Provider: map[string]any{"k3s": map[string]any{"enabled": true}}})
		Expect(err).ToNot(HaveOccurred())
		Expect(out).To(ContainSubstring("k3s:\n    enabled: true\n"))
	})
})

var _ = Describe("RenderRedacted and Redact", func() {
	It("replaces the password hash and never leaks it", func() {
		out, err := wizard.RenderRedacted(wizard.Answers{Disk: "/dev/sda", Username: "kairos", PasswordHash: "$6$salt$supersecrethash"})
		Expect(err).ToNot(HaveOccurred())
		Expect(out).To(ContainSubstring(wizard.Redacted))
		Expect(out).ToNot(ContainSubstring("supersecrethash"))
	})

	It("redacts every passwd key in hand-edited YAML, at any depth", func() {
		in := "#cloud-config\nusers:\n  - name: a\n    passwd: plain1\nstages:\n  boot:\n    - users:\n        b:\n          passwd: $6$x$secret2\n"
		out := wizard.Redact(in)
		Expect(out).ToNot(ContainSubstring("plain1"))
		Expect(out).ToNot(ContainSubstring("secret2"))
		Expect(out).To(HavePrefix("#cloud-config\n"))
	})

	It("returns a placeholder instead of the text when the YAML does not parse", func() {
		Expect(wizard.Redact("users: [unterminated\n  passwd: leak")).ToNot(ContainSubstring("leak"))
	})
})
