name: Unit tests
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
env:
  FORCE_COLOR: 1
concurrency:
  group: ci-unit-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Setup Go environment
        uses: actions/setup-go@v7.0.0
        with:
          go-version-file: go.mod
      - name: Run tests
        run: |
          go run github.com/onsi/ginkgo/v2/ginkgo run -p --github-output  --covermode=atomic --coverprofile=coverage.out --race -r ./...
      - name: Codecov
        uses: codecov/codecov-action@v7
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./coverage.out
