name: goreleaser

on:
  push:
    branches:
      - 'test-goreleaser/**'
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: |
          git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'
      - name: (dry-run) GoReleaser
        if: startsWith(github.ref_name, 'test-goreleaser')
        uses: goreleaser/goreleaser-action@v7
        with:
          version: latest
          args: release --skip=validate,publish
      - name: Run GoReleaser
        if: startsWith(github.ref_name, 'test-goreleaser') != true
        uses: goreleaser/goreleaser-action@v7
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
