name: Unit tests
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: test-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.repository }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: Run tests
        run: |
          go run github.com/onsi/ginkgo/v2/ginkgo --fail-fast --covermode=atomic --coverprofile=coverage.out -p -r ./internal
      - name: Codecov
        uses: codecov/codecov-action@v7
        with:
          file: ./coverage.out
      - name: Generate version
        run: echo "VERSION=$(git describe --always --tags --dirty)" >> $GITHUB_ENV
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          version: latest
          args: --snapshot --clean
      - uses: actions/upload-artifact@v7
        with:
          name: build.zip
          path: |
            dist/*
