name: 'Build AMD64 images (Master)'

on:
  push:
    branches:
      - master

permissions:
  contents: write
  security-events: write
  id-token: write
  actions: read
concurrency:
  group: ci-amd64-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
jobs:
  build:
    name: ${{ matrix.image_name }}
    uses: kairos-io/kairos-factory-action/.github/workflows/reusable-factory.yaml@84ea9b020bdd470081b235a1a99147a98d32c989 # v1.1.1
    secrets:
      registry_username: ${{ secrets.QUAY_USERNAME }}
      registry_password: ${{ secrets.QUAY_PASSWORD }}
    with:
      auroraboot_version: "v0.19.4"
      dockerfile_path: "images/Dockerfile"
      base_image: ${{ matrix.base_image }}
      model: "generic"
      arch: "amd64"
      version: "auto"
      iso: true
      grype: true
      security_scan_mode: "enforce"
      registry_domain: "quay.io"
      registry_namespace: "kairos"
      registry_repository: "ci-temp-images"
      custom_tag_format: "$FLAVOR-$FLAVOR_RELEASE-$VARIANT-$ARCH-$MODEL-$COMMIT_SHA"
      custom_artifact_format: "kairos-$FLAVOR-$FLAVOR_RELEASE-$VARIANT-$ARCH-$MODEL"
      custom_job_name_format: ${{ matrix.custom_job_name_format }}
      image_labels: "quay.expires-after=2w"
      summary_artifacts: true
      kubernetes_distro: ${{ matrix.kubernetes_distro }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - image_name: "hadron"
            base_image: "ghcr.io/kairos-io/hadron:v0.0.4"
            kubernetes_distro: ""
            custom_job_name_format: "core-amd64-generic"
          - image_name: "hadron"
            base_image: "ghcr.io/kairos-io/hadron:v0.0.4"
            kubernetes_distro: "k3s"
            custom_job_name_format: "standard-amd64-generic-k3s"
