name: Unit tests
on:
  push:
    branches:
      - main
  pull_request:
env:
  FORCE_COLOR: 1
concurrency:
  group: ci-unit-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Go environment
        uses: actions/setup-go@v6.4.0
        with:
          go-version-file: go.mod
      - name: Run tests
        run: |
          go run github.com/onsi/ginkgo/v2/ginkgo run -p --github-output --covermode=atomic --coverprofile=coverage.out --race -r ./...
