# https://goreleaser.com
version: 2
builds:
  - ldflags:
      - -w -s
      - -X github.com/kairos-io/kairos-installer/internal/tui.version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - riscv64
    binary: '{{ .ProjectName }}'
    id: default
source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Tag }}-source'
archives:
  - id: default-archive
    ids:
      - default
    name_template: '{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}-{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
checksum:
  name_template: '{{ .ProjectName }}-{{ .Tag }}-checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge pull request'
before:
  hooks:
    - go mod tidy
